image: alpine/edge
packages:
  - go
sources:
  - https://github.com/go-ap/storage-conformance-suite
tasks:
  - tests: |
      cd storage-conformance-suite
      go test -cover -race -count=1 -json ./... | go run github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt -showteststatus
  - storage-fs: |
      ./storage-conformance-suite/tools/run-suite.sh https://github.com/go-ap/storage-fs
  - storage-boltdb: |
      ./storage-conformance-suite/tools/run-suite.sh https://github.com/go-ap/storage-boltdb
  - storage-badger: |
      ./storage-conformance-suite/tools/run-suite.sh https://github.com/go-ap/storage-badger
  - storage-sqlite: |
      ./storage-conformance-suite/tools/run-suite.sh https://github.com/go-ap/storage-sqlite
  - storage-sqlite-v2: |
      ./storage-conformance-suite/tools/run-suite.sh https://git.sr.ht/~mariusor/storage-sqlite storage-sqlite-v2
